env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  no-console: 0
  no-unused-vars:
    - warn
  # indent:
  #   - error
  #   - 4
  # linebreak-style:
  #   - error
  #   - unix
  # quotes:
  #   - error
  #   - single
  # semi:
  #   - error
  #   - always
